'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.34014
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RtCWGH.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Cheat 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ac_tivate Base Cheating Function 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BaseCheatFunc_ActivateCheat() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BaseCheatFunc_ActivateCheat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cheating Function 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BaseCheatFunc_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BaseCheatFunc_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Add 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Add() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Another Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_AnotherSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_AnotherSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 A_pply 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Apply() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Clear All 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_ClearAll() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_ClearAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Delete 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Delete() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cheating Key Binding 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_HeaderMain() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_HeaderMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Command 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_ListHead_Cmd() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_ListHead_Cmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Key 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_ListHead_Key() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_ListHead_Key", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_MainSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_MainSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Home 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_HomeHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_HomeHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Chinese Localized(Only for China) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Install 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_Install() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Load Localization Package 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_LoadLocalizedPackage() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_LoadLocalizedPackage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Warning:This localization package is only used in China.
        '''
        '''The localization package is made by Leyuxiaoyao(http://hi.baidu.com/乐雨逍遥),Leyuxiaoyao All Right reserved.
        '''
        '''This package is only for Original RTCW Maps, none for Mods.
        '''
        '''Two ways to install:
        '''&quot;Install into Main Folder&quot;, I will install the package into the Main Folder and RTCW will load the package Automatically. By this way,the package will be loaded all the time. Some mod menu will be of dislocation. Your saved files are in Main Folder.
        '''
        '''&quot;Inst [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_LocalizedDescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_LocalizedDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Uninstall 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_Uninstall() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_Uninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Mod 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Replace qagamex86.dll And cgamex86.dll automatically 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_ActivateAutoReplacement() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_ActivateAutoReplacement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Map Mod 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Run Mod Menu 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_ModMap_EnterModMenu() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_ModMap_EnterModMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Maps 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_ModMap_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_ModMap_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Load 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_ModMap_Load() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_ModMap_Load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Map Name 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_ModMap_MapName() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_ModMap_MapName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 PK3 Address 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_ColAddress() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_ColAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Map Count 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_ColMapCount() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_ColMapCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 PK3 Name 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_ColPK3Name() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_ColPK3Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Type 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_ColWay() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_ColWay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 PK3 List 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Install PK3... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_Install() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Refresh 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_Refresh() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Uninstall PK3 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_MapMod_PK3List_Uninstall() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_MapMod_PK3List_Uninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resource Mod 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 PK3 Address 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_PK3List_ColAddress() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_PK3List_ColAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resource Type 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_PK3List_ColResType() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_PK3List_ColResType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 PK3 List 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_PK3List_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_PK3List_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Install PK3... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_PK3List_Install() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_PK3List_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Refresh 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_PK3List_Refresh() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_PK3List_Refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Uninstall PK3 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_ModPage_ResMod_PK3List_Uninstall() As String
            Get
                Return ResourceManager.GetString("MainWindow_ModPage_ResMod_PK3List_Uninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Other 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Config File 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_GameFunction_ConfigFile_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_GameFunction_ConfigFile_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Reset Config File 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_GameFunction_ConfigFile_Reset() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_GameFunction_ConfigFile_Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 qagamex86.dll And cgamex86.dll 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_GameFunction_Dll_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_GameFunction_Dll_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 R_eset These Dll 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_GameFunction_Dll_Reset() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_GameFunction_Dll_Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Game Function 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_GameFunction_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_GameFunction_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Another Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_AnotherSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_AnotherSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Apply 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Apply() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Fov value now is {0},Default is 90 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Fov_Description() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Fov_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Fov 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Fov_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Fov_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Other Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_MainSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_MainSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Custom Resolution 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Resolution_CustomResolution() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Resolution_CustomResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Resolution 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Resolution_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Resolution_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get Now Resolution 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Resolution_NowResolution() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Resolution_NowResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Internal Resolution 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Resolution_UseInternalResolution() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Resolution_UseInternalResolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Screenshot 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Screenshot_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Screenshot_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 JPEG Shot 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Screenshot_JPEGDescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Screenshot_JPEGDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 TGA Shot 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Screenshot_TGADescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Screenshot_TGADescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tip 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Screenshot_Tip() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Screenshot_Tip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 F11 is default TGA screenshot key in RtCW. If you don&apos;t bind F11 on other command, RtCW will reset F11 as default TGA screenshot key. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_OtherPage_OtherSetting_Screenshot_TipDescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_OtherPage_OtherSetting_Screenshot_TipDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Saves 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SaveHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_SaveHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Load Original Map 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_LoadOrgMap_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_LoadOrgMap_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Load 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_LoadOrgMap_LoadButton() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_LoadOrgMap_LoadButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Map Name 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_LoadOrgMap_MapName() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_LoadOrgMap_MapName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Add 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_Add() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Another Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_AnotherSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_AnotherSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 A_pply 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_Apply() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Load Key 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_ColLoadKey() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_ColLoadKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save Key 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_ColSaveKey() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_ColSaveKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save Name 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_ColSaveName() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_ColSaveName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Delete 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_Delete() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 In RTCW,you can save by F5 key. Now you can bind more auto saving key. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_Description() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Saving Hotkey Definition 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveHotKey_MainSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveHotKey_MainSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Other Saves 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_AnotherSave() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_AnotherSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Auto Saves 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_AutoSaves() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_AutoSaves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Total Game Time 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_ColGameTime() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_ColGameTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Health 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_ColHeath() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_ColHeath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Map Name 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_ColMapName() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_ColMapName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Saves Name 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_ColSaveName() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_ColSaveName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Change Time 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_ColTime() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_ColTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Saves Manager 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main Saves 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_MainSave() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_MainSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Normal Saves 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_SavePage_SaveMgr_NormalSaves() As String
            Get
                Return ResourceManager.GetString("MainWindow_SavePage_SaveMgr_NormalSaves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RTCW Game Helper is a game assistant for RTCW.With this assistant,all the players can play RTCW easilier. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_Description() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Features:
        '''Saves Manager
        '''Cheat Manager
        '''Mod Manager... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_FunctionDescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_FunctionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Reset Folder and Version Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_ResetFolderNVersion() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_ResetFolderNVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Start Game 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_StartGame() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_StartGame", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
