'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.34014
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RtCWGH.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Cheat 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ac_tivate Base Cheating Function 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BaseCheatFunc_ActivateCheat() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BaseCheatFunc_ActivateCheat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cheating Function 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BaseCheatFunc_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BaseCheatFunc_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Add 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Add() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Another Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_AnotherSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_AnotherSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 A_pply 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Apply() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Clear All 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_ClearAll() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_ClearAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Delete 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Delete() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Cheating Key Binding 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_Header() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_HeaderMain() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_HeaderMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Command 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_ListHead_Cmd() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_ListHead_Cmd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Key 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_ListHead_Key() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_ListHead_Key", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Main Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_CheatPage_BindCheatHotKey_MainSetting() As String
            Get
                Return ResourceManager.GetString("MainWindow_CheatPage_BindCheatHotKey_MainSetting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Home 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_HomeHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_HomeHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Chinese Localized(Only for China) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedHeader() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Install 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_Install() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Load Localization Package 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_LoadLocalizedPackage() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_LoadLocalizedPackage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Warning:This localization package is only used in China.
        '''
        '''The localization package is made by Leyuxiaoyao(http://hi.baidu.com/乐雨逍遥),Leyuxiaoyao All Right reserved.
        '''
        '''This package is only for Original RtCW Maps, none for Mods.
        '''
        '''Two ways to install:
        '''&quot;Install into Main Folder&quot;, I will install the package into the Main Folder and RtCW will load the package Automatically. By this way,the package will be loaded all the time. Some mod menu will be of dislocation. Your saved files are in Main Folder.
        '''
        '''&quot;Inst [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_LocalizedDescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_LocalizedDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Uninstall 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_LocalizedPage_Uninstall() As String
            Get
                Return ResourceManager.GetString("MainWindow_LocalizedPage_Uninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RtCW Game Helper is a game assistant for RtCW.With this assistant,all the players can play RtCW easilier. 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_Description() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Features:
        '''Saves Manager
        '''Cheat Manager
        '''Mod Manager... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_FunctionDescription() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_FunctionDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Reset Folder and Version Setting 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_ResetFolderNVersion() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_ResetFolderNVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 _Start Game 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MainWindow_StartPage_StartGame() As String
            Get
                Return ResourceManager.GetString("MainWindow_StartPage_StartGame", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
